---

install_tools:
  - byobu
  - curl
  - htop
  - tree
  - vim-enhanced
  - mc
  - tig
  - apg
  - wget
  - nano
  - http://opensource.wandisco.com/centos/7/git/x86_64/git-2.7.4-1.WANdisco.293.x86_64.rpm
  - http://opensource.wandisco.com/centos/7/git/x86_64/perl-Git-2.7.4-1.WANdisco.293.noarch.rpm

install_dev:
  - autoconf
  - automake
  - libuuid-devel
  - libxml2-devel
  - python2-pip
  - python-psycopg2
  - python-pyasn1
  - freetds-devel

install_dev_pip:
  - urllib3
  - ndg-httpsclient

uninstall_unwanted:
  - nothing_yet
